### ISSUE TITLE
Problem with MRT on NextJS

### ISSUE THREAD

**Issue by Linux-Alex** [KevinVandy/material-react-table#1346]
### material-react-table version

3.1.0

### react & react-dom versions

19.0.0

### Describe the bug and the steps to reproduce it

I am having problems implementing a basic table in my React v19, Next.js v15.1.3, and TypeScript project.

I encounter the following error:
```
TypeError: Cannot read properties of undefined (reading 'type')
    at decomposeColor (http://localhost:3000/_next/static/chunks/node_modules_27dee3._.js:3044:15)
    at lighten (http://localhost:3000/_next/static/chunks/node_modules_27dee3._.js:3213:13)
    at getMRTTheme (http://localhost:3000/_next/static/chunks/node_modules_material-react-table_dist_index_esm_dd6270.js:1034:564)
    at useMRT_TableOptions.useMemo (http://localhost:3000/_next/static/chunks/node_modules_material-react-table_dist_index_esm_dd6270.js:1985:44)
    at mountMemo (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:3703:25)
    at Object.useMemo (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:12520:24)
    at exports.useMemo (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_107ce8._.js:1867:36)
    at useMRT_TableOptions (http://localhost:3000/_next/static/chunks/node_modules_material-react-table_dist_index_esm_dd6270.js:1984:189)
    at useMaterialReactTable (http://localhost:3000/_next/static/chunks/node_modules_material-react-table_dist_index_esm_dd6270.js:2406:68)
    at MaterialReactTable (http://localhost:3000/_next/static/chunks/node_modules_material-react-table_dist_index_esm_dd6270.js:6702:17)
    at react-stack-bottom-frame (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:13403:24)
    at renderWithHooks (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:2977:24)
    at updateFunctionComponent (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:4732:21)
    at beginWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:5364:24)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7955:97)
    at workLoopSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7847:40)
    at renderRootSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7830:13)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7589:56)
    at performWorkOnRootViaSchedulerTask (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8394:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_107ce8._.js:2353:64)
```

I tried creating a new project and importing only the necessary libraries. I also ensured that I typed all variables, such as `data` and `columns`, but nothing seems to resolve the issue.

### Minimal, Reproducible Example - (Optional, but Recommended)

```ts
"use client";

import React from "react";
import { MaterialReactTable } from "material-react-table";

const data = [
  { firstName: "John", lastName: "Doe", age: 30 },
  { firstName: "Jane", lastName: "Smith", age: 25 },
];

const columns = [
  { accessorKey: "firstName", header: "First Name" },
  { accessorKey: "lastName", header: "Last Name" },
  { accessorKey: "age", header: "Age" },
];

const Example = () => {
  try {
    return <MaterialReactTable columns={columns} data={data} />;
  } catch (error) {
    console.error("Error rendering table:", error);
    return <div>Error loading table.</div>;
  }
  
};

export default Example;
```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by mjulstein** [comment]
I pasted the exact same code into my next-15 project and did not get the Type-errors in dev mode.
I built it with Next 15.1.4 without issues either.
Maybe you could update all your type and typescript dependencies?
