### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by Drezir** [KevinVandy/material-react-table#391]
### material-react-table version

1.7.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Error when filtering in "range" mode.

```json
    {
        size: 250,
        accessorKey: "credit",
        filterVariant: "range",
        header: i18n.t("document.credit"),
        muiTableBodyCellProps: {
            align: "right",
        },
    },
```

```
MRT_FilterTextField.tsx:153 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at MRT_FilterTextField.tsx:153:1
    at functionalUpdate (utils.ts:77:1)
    at Filters.ts:275:1
    at functionalUpdate (utils.ts:77:1)
    at updateFn (Filters.ts:380:1)
    at basicStateReducer (react-dom.development.js:16540:1)
    at updateReducer (react-dom.development.js:16664:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1)
```

### Minimal, Reproducible Example - (Optional, but Recommended)

Sorry

### Screenshots or Videos (Optional)

[Kooha-2023-02-22-14-02-09.webm](https://user-images.githubusercontent.com/11374081/220627188-f0505d81-91b3-4500-8df7-a43e970f4469.webm)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Drezir** [comment]
I have discovered that this happens if I pass initial state (filters in this case) to table via initialState property

**Comment by Drezir** [comment]
I am initializing and changing state from/to redux and I am using server side pagination, sorting etc. This happens when I init state using, for example: [sorting, setSorting] = React.useState(initSortingState). I think this was a mistake so I fixed it by using initialState as table property

initFilter is just object of manual pagination and sorting.
```js
                initialState={{
                    ...initFilter,
                    ...initialState,
                }}
```

State passes to the table well but when manual sort is used nothing is actually initialized. I think I must use effect to init states on mount. Is this correct?

**Comment by KevinVandy** [comment]
I believe you, but have not been able to reproduce this if passing in valid initialState filters. I might as well add an internal Array.isArray check to prevent bad filter types from causing this
